// This program is part of a project that generates follow-up files for the PSPLIB benchmarks, 
// specifically for the J30 problem set. 
// The program calculates the follow-ups corresponding to MR4 based on the original .dzn files,
// where the value of the components of rc that correspond 
// to the bound of the available resources is increased.

// In the file j30_1_1.dzn are available 4 resources (n_res = 4) with bounds rc = [ 12, 13, 4, 12 ];
//  n_res = 4;
//  rc = [ 12, 13, 4, 12 ];
// and the follow-ups are generated by multiplying by 2 the value of each component of rc.

// File j30_1_1_fu_rc1.dzn contains rc = [ 24, 13, 4, 12 ];




#include <iostream>
#include <fstream>
#include <iterator>
#include <string>
#include <regex>
using namespace std;

void process(string file_name, string fu_name);
void process_all(string file_name, string fu_name);

struct tFiles {
	string nombre = "";
	string texto = "";
};

int main() {

	string path_file = "../benchmarks/data/data_psplib/j30/J30";
	string path_fu = "../benchmarks/data/data_psplib_follow_ups/MR4/j30/J30";

	process_all(path_file, path_fu);
}

void process_all(string path_file, string path_fu) {

	for (int i = 1; i <= 48; i++) {  // 48
		for (int j = 1; j <= 10; j++) {  // 10
			string path_file_aux = path_file + "_" + to_string(i) + "_" + to_string(j);
			string path_fu_aux = path_fu + "_" + to_string(i) + "_" + to_string(j);
			process(path_file_aux, path_fu_aux);
		}
	}
}

void process(string file_name, string fu_name) {

	ifstream in(file_name + ".dzn");

	std::string s = "";

	// First line  n_res = ? 
	int n_res = 0;
	getline(in, s);

	// Work with regular expressions to remove = ; [ ]
	std::regex word_regex("(\\w+)");

	// iterators  https://runebook.dev/es/docs/cpp/regex?
	std::sregex_iterator i = std::sregex_iterator(s.begin(), s.end(), word_regex);
	std::smatch match = *i;
	std::string match_str = match.str();
	if (match_str.compare("n_res") == 0) {
		++i;
		match = *i;
		match_str = match.str();
		n_res = stoi(match_str);  // casting from string to int
	}

	// Need to create as many follow-ups as n_res

	tFiles* array_files = new tFiles[n_res];

	int cont1 = 0;
	// All output files have the same first line: array_files[cont2].texto = s; 
	while (cont1 < n_res) {
		array_files[cont1].nombre = fu_name + "_fu_rc_" + to_string(cont1 + 1) + ".dzn";
		array_files[cont1].texto = s;
		cont1++;
	}

	// The second line is of the form rc = [...]
	getline(in, s);
	i = std::sregex_iterator(s.begin(), s.end(), word_regex);

	string* array_din_rc = new string[n_res];

	match = *i;
	match_str = match.str();
	if (match_str.compare("rc") == 0) {

		// Store the data rc = [ 12, 13, 4, 12 ]; in a dynamic array array_din_rc
		for (int k = 0; k < n_res; k++) {
			++i;
			match = *i;
			match_str = match.str();
			array_din_rc[k] = match_str;
		}

		// Generate the output
		cont1 = 0;
		int* array_din_rc_aux = new int[n_res];
		while (cont1 < n_res) {
			string aux = "";
			aux += "\nrc = [ ";

			for (int k = 0; k < n_res; k++) {
				array_din_rc_aux[k] = stoi(array_din_rc[k]);
				if (k == cont1) {
					array_din_rc_aux[k] = 2 * array_din_rc_aux[k];
				}
				aux += to_string(array_din_rc_aux[k]);   // add element by element
				if (k < n_res - 1) aux += ", ";
			}
			aux += " ];\n";
			array_files[cont1].texto += aux;
			cont1++;
		}
		delete[] array_din_rc_aux;
	}

	// The rest of the lines are read and written directly because they do not change

	getline(in, s);
	while (in) {
		for (int i = 0; i < n_res; i++) {
			array_files[i].texto += s + "\n";
		}
		getline(in, s);
	}

	// Now I pass all the information I have in array_files
	// For each element of the array array_files I generate a file

	for (size_t i = 0; i < n_res; i++) {
		ofstream output_file(array_files[i].nombre);
		output_file << array_files[i].texto;
		output_file.close();
	}

	delete[] array_din_rc;
	delete[] array_files;
	in.close();
}
